# Configuration file for gateway-service

server:
  port: 8085
logging:
  level:
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: get-book-by-title
          uri: http://localhost:8080/books/{title}  #lb://BOOKS-SERVICE/
          predicates:
            - Method=GET
            - Path=/books/{title}

        - id: get-book-by-author
          uri: http://localhost:8080/books/{author}   #lb://BOOKS-SERVICE/
          predicates:
            - Method=GET
            - Path=/books/{author}

        #        - id: create-new-book
        - id: save
          uri: http://localhost:8080/api/v1/books  #lb://BOOKS-SERVICE/
          predicates:
            - Method=POST
            - Path=/books

        - id: create-new-author
#          uri: http://localhost:8080/authors/create #lb://AUTHORS-SERVICE
          uri: http://localhost:8080/authors #lb://AUTHORS-SERVICE
          predicates:
            - Method=POST
            - Path=/authors

#        - id: get-author-by-name
#          uri: http://localhost:8080/authors/{name}       #lb://AUTHORS-SERVICE/
#          predicates:
#            - Method=GET
#            - Path=/authors/{name}
        - id: get-all-author
          uri: http://localhost:8080/authors/{allAuthors}       #lb://AUTHORS-SERVICE/
          predicates:
            - Method=GET
            - Path=/authors/{name}

        - id: get-book-by-author-name
          uri: http://localhost:8080/authors/{name}/books  #lb://AUTHORS-SERVICE/
          predicates:
            - Method=GET
            - Path=/authors/{name}/books
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true